
SECRET_KEY_BASE: "00cc3dd0867d8dff03fb9e3778e4a5198f22633f88385635323b59d7dc5ec8cabe6d87d07ab6e011f4974163e864f54e61d6fcfbac0f41426c05688a96625ae7"
SEND_EMAIL: "false"
RAISE_DELIVERY_ERRORS: "false"
DEFAULT_FROM_ADDRESS: "yourmail@gmail.com"

# Configuration values for Oauth through Google
GOOGLE_CLIENT_ID: ""
GOOGLE_CLIENT_SECRET: ""
GOOGLE_APP_NAME: "" #this is the project name you configured when setting up your google client application

# Configuration values for pusher
PUSHER_APP_ID: ""
PUSHER_KEY: ""
PUSHER_SECRET: ""

# Configuration values for cloudinary
CLOUDINARY_CLOUD_NAME: ""
CLOUDINARY_API_KEY: ""
CLOUDINARY_API_SECRET: ""

#configuration for smtp
SMTP_USER_NAME: "funmiesho@gmail.com"
SMTP_PASSWORD: "funmilayo1991"
SMTP_PORT:  "465"
SMTP_ADDRESS: "smtp.gmail.com"
